### ISSUE TITLE
[nodemon] app crashed

### ISSUE THREAD

**Issue by skoropadas** [nmanikiran/rest-api-node-typescript#1]
I wanted to see your project, but I have this error
`[nodemon] app crashed - waiting for file changes before starting...`
help me please

**Comment by nmanikiran** [comment]
1) you need to install PostgreSQL  and then set the  following environment variable 
      `C:\Program Files\PostgreSQL\10\bin`
      `C:\Program Files\PostgreSQL\10\lib`
2) in the db.ts file the DB connection string need to be updated accoring to your `credentials`.
      ex : `postgres://<YourUserName>:<YourPassword>@localhost:5432/<YourDatabase>`
3) import the `.sql` files which you can find under db folder

Thanks for reaching out and I updated readme.md file accordingly

**Comment by skoropadas** [comment]
I did it of course. but the problem was solved in a magical way, thanks anyway!
